config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  root 'dashboard#index'
  delete 'users/:id' => 'users#destroy', :as => :admin_destroy_user

  resources :patient_registrations, only: [:new, :create, :index]
  resources :departments, only: [:new, :create, :index]
  resources :employees, only: [:new, :create, :index, :edit, :update]
  resources :employee_types, only: [:new, :create, :index, :edit, :update]
  resources :shifts, only: [:new, :create, :index]
  resources :duty_entities, only: [:new, :create, :index]
  resources :duty_sheets, only: [:new, :create, :index]
  resources :groups, only: [:new, :create, :index, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :patient_entry
  belongs_to :billing_entity
end

app/models/billing_entity.rb
class BillingEntity < ApplicationRecord
  has_many :bills
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :patient_entries
end

app/models/duty_entity.rb
class DutyEntity < ApplicationRecord
  has_many :duty_sheets
end

app/models/duty_sheet.rb
class DutySheet < ApplicationRecord
  belongs_to :employee
  belongs_to :ward
  belongs_to :duty_entity
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :employee_type
  has_many :duty_sheets
end

app/models/employee_type.rb
class EmployeeType < ApplicationRecord
  has_many :employees
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :shift
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  belongs_to :patient_entry
end

app/models/patient_entry.rb
class PatientEntry < ApplicationRecord
  has_many :bills
  has_many :medicines
  has_many :test_reports
  belongs_to :department
  belongs_to :patient_registration
  belongs_to :patient_registration_type
  belongs_to :doctor_appointment_sheet
end

app/models/shift.rb
class Shift < ApplicationRecord
  has_many :groups
end

app/models/test_report.rb
class TestReport < ApplicationRecord
  belongs_to :patient_entry
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :ward_type
  has_many :duty_sheets
end

app/models/ward_type.rb
class WardType < ApplicationRecord
  has_many :wards
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user!

  def index
    @employee_types = EmployeeType.all
    @employees = Employee.all
    @groups = Group.all
    @employee_type = EmployeeType.new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_path, flash: {success: 'New employee added successfully.'}
    else
      redirect_to :back
    end
  end

  def edit
    @employee_types = EmployeeType.all
    @groups = Group.all
    @employee = Employee.find(params[:id])
  end

  def update
    @employee= Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to employees_path
    else
      render :edit
    end
  end

  private

  def unique_check
    if Employee.find_by(contact_number: params[:employee][:contact_number]).present? || Employee.find_by(email: params[:employee][:email]).present?
      redirect_to employee_index_path
    end
  end

  def employee_params
    params.require(:employee).permit(:first_name, :last_name, :contact_number,
                                     :alternate_contact_number, :email, :address_line,
                                     :city, :state, :country, :pincode, :employee_type_id,
                                     :gender, :govt_id, :govt_id_type, :group_id)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/patient_helper.rb
module PatientHelper
  def gender(val)
    gender = {"1" => "Male", "2" => "Female", "3" => "Others"}
    gender[val]
  end
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/employee/_form.html.erb
<button type="button" class="btn btn-primary expanded-button" data-toggle="modal" data-target="#designationModal">Add Designation</button>
<div class="modal fade" id="designationModal" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <span class="modal-title">Add Designation</span>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <%= form_for employee_index_path, method: 'post' do |f| %>
            <div class="row button-inline-align">
              <div class="col-sm-6">
                <label for="name">Designation Name:</label>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="col-sm-6">
                <%= f.submit "Add Designation Type", class: 'btn btn-primary expanded-button' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employee/_index.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= render "form" %>
  </div>
  <div class="col-sm-6">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Index</th>
        <th>Name</th>
      </tr>
      </thead>
      <div class="table-scrollable">
      <tbody>
      <% @employee_types.each do |f| %>
        <tr>
          <td><%= f.id %></td>
          <td><%= f.name %></td>
        </tr>
      <% end %>
      </tbody>
      </div>
    </table>
  </div>
</div>

app/views/employee/_new_employee_form.html.erb
<button type="button" class="btn btn-primary expanded-button" data-toggle="modal" data-target="#employeeModal">Add Employee</button>
<div class="modal fade" id="employeeModal" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <span class="modal-title">Add Employee</span>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <%= form_for employee_index_path, method: 'post' do |f| %>
            <div class="row button-inline-align">
              <div class="col-sm-3">
                <label for="employee_type">Employee Type:</label><br>
                <%= f.select :employee_type_id, options_from_collection_for_select(@employee_types, 'id', 'name'), {}, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="first_name">First Name:</label>
                <%= f.text_field :first_name, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="last_name">Last Name:</label>
                <%= f.text_field :last_name, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="gender">Gender:</label><br>
                <%= f.select :gender, options_for_select([["Male", 1], ["Female", 2], ["Others", 3]]), {}, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="contact_number">Contact Number:</label>
                <%= f.text_field :contact_number, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="alternate_contact_number">Alternate Contact:</label>
                <%= f.text_field :alternate_contact_number, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="email">Email:</label>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="address_line">Address Line:</label>
                <%= f.text_field :address_line, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="city">City:</label>
                <%= f.text_field :city, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="state">State:</label>
                <%= f.text_field :state, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="country">Country:</label>
                <%= f.text_field :country, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="pincode">Pincode:</label>
                <%= f.text_field :pincode, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="govt_id_type">Govt ID Type:</label><br>
                <%= f.select :govt_id_type, options_for_select([["License", 1], ["Passport", 2], ["Aadhar", 3]]), {}, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="govt_id">Govt ID:</label>
                <%= f.text_field :govt_id, class: 'form-control' %>
              </div>
              <div class="col-sm-6">
                <br>
                <%= f.submit "Create", class: 'btn btn-primary expanded-button' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employee/index.html.erb
<h3>Employee</h3>
<div class="row option-header">
  <div class="col-sm-2">
    <%= render "new_employee_form" %>
  </div>
  <div class="col-sm-2">
    <%= render "form" %>
  </div>
</div>
<div class="row">
  <div class="col-sm-10">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Profession</th>
        <th>Gender</th>
        <th>Contact</th>
        <th>Address</th>
      </tr>
      </thead>
      <tbody>
      <% @employees.each do |f| %>
        <tr>
          <td><%= f.first_name %> <%= f.last_name %></td>
          <td><%= @employee_types.find(f.employee_type_id).name %></td>
          <td><%= gender(f.gender) %></td>
          <td><%= f.contact_number %>, <%= f.alternate_contact_number %></td>
          <td><%= f.address_line %>, <%= f.city %>, <%= f.country %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-sm-2">
    <%= render partial: "index" %>
  </div>
</div>

app/views/employees/_employee_update_form.html.erb
<div class="form-group">
  <%= form_for @employee do |f| %>
    <div class="row button-inline-align">
      <div class="col-sm-3">
        <label for="employee_type">Employee Type:</label><br>
        <%= f.select :employee_type_id, options_from_collection_for_select(@employee_types, 'id', 'name', {:selected => f.object.employee_type_id}), {}, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="first_name">First Name:</label>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="last_name">Last Name:</label>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="gender">Gender:</label><br>
        <%= f.select :gender, options_for_select([["Male", 1], ["Female", 2], ["Others", 3]], :selected => f.object.gender), {}, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="contact_number">Contact Number:</label>
        <%= f.text_field :contact_number, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="alternate_contact_number">Alternate Contact:</label>
        <%= f.text_field :alternate_contact_number, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="email">Email:</label>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="address_line">Address Line:</label>
        <%= f.text_field :address_line, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="city">City:</label>
        <%= f.text_field :city, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="state">State:</label>
        <%= f.text_field :state, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="country">Country:</label>
        <%= f.text_field :country, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="pincode">Pincode:</label>
        <%= f.text_field :pincode, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="govt_id_type">Govt ID Type:</label><br>
        <%= f.select :govt_id_type, options_for_select([["License", 1], ["Passport", 2], ["Aadhar", 3]], :selected => f.object.govt_id_type), {}, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="govt_id">Govt ID:</label>
        <%= f.text_field :govt_id, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <label for="group_id">Group:</label><br>
        <%= f.select :group_id, options_from_collection_for_select(@groups, 'id', 'name', {:selected => f.object.group_id}), {}, class: 'form-control' %>
      </div>
      <div class="col-sm-3">
        <br>
        <%= f.submit "Update", class: 'btn btn-primary expanded-button' %>
      </div>
    </div>
  <% end %>
</div>

app/views/employees/_new_employee_form.html.erb
<button type="button" class="btn btn-primary expanded-button" data-toggle="modal" data-target="#employeeModal">Add Employee</button>
<div class="modal fade" id="employeeModal" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <span class="modal-title">Add Employee</span>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <%= form_for @employee, method: 'post' do |f| %>
            <div class="row button-inline-align">
              <div class="col-sm-3">
                <label for="employee_type">Employee Type:</label><br>
                <%= f.select :employee_type_id, options_from_collection_for_select(@employee_types, 'id', 'name'), {}, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="first_name">First Name:</label>
                <%= f.text_field :first_name, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="last_name">Last Name:</label>
                <%= f.text_field :last_name, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="gender">Gender:</label><br>
                <%= f.select :gender, options_for_select([["Male", 1], ["Female", 2], ["Others", 3]]), {}, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="contact_number">Contact Number:</label>
                <%= f.text_field :contact_number, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="alternate_contact_number">Alternate Contact:</label>
                <%= f.text_field :alternate_contact_number, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="email">Email:</label>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="address_line">Address Line:</label>
                <%= f.text_field :address_line, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="city">City:</label>
                <%= f.text_field :city, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="state">State:</label>
                <%= f.text_field :state, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="country">Country:</label>
                <%= f.text_field :country, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="pincode">Pincode:</label>
                <%= f.text_field :pincode, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="govt_id_type">Govt ID Type:</label><br>
                <%= f.select :govt_id_type, options_for_select([["License", 1], ["Passport", 2], ["Aadhar", 3]]), {}, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="govt_id">Govt ID:</label>
                <%= f.text_field :govt_id, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <label for="group_id">Group:</label><br>
                <%= f.select :group_id, options_from_collection_for_select(@groups, 'id', 'name'), {}, class: 'form-control' %>
              </div>
              <div class="col-sm-3">
                <br>
                <%= f.submit "Create", class: 'btn btn-primary expanded-button' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<%= render 'employee_update_form' %>

app/views/employees/index.html.erb
<h3>Employee</h3>
<div class="row option-header">
  <div class="col-sm-2">
    <%= render "new_employee_form" %>
  </div>
  <div class="col-sm-2">
    <%= render "employee_types/form" %>
  </div>
</div>
<div class="row">
  <div class="col-sm-10">
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Name</th>
        <th>Profession</th>
        <th>Gender</th>
        <th>Contact</th>
        <th>Address</th>
        <th>Group</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @employees.each do |f| %>
        <tr>
          <td><%= f.first_name %> <%= f.last_name %></td>
          <td><%= @employee_types.find(f.employee_type_id).name %></td>
          <td><%= gender(f.gender) %></td>
          <td><%= f.contact_number %>, <%= f.alternate_contact_number %></td>
          <td><%= f.address_line %>, <%= f.city %>, <%= f.country %></td>
          <td><%= @groups.find(f.group_id).name %></td>
          <td><%= link_to 'Edit', edit_employee_path(f.id) %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-sm-2">
    <%= render partial: "employee_types/index" %>
  </div>
</div>