config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }
  root 'dashboard#index'
  delete 'users/:id' => 'users#destroy', :as => :admin_destroy_user

  resources :patient_registrations, only: [:new, :create, :index]
  resources :departments, only: [:new, :create, :index]
  resources :employees, only: [:new, :create, :index, :edit, :update]
  resources :employee_types, only: [:new, :create, :index, :edit, :update]
  resources :shifts, only: [:new, :create, :index]
  resources :duty_entities, only: [:new, :create, :index]
  resources :duty_sheets, only: [:new, :create, :index]
  resources :groups, only: [:new, :create, :index, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :patient_entry
  belongs_to :billing_entity
end

app/models/billing_entity.rb
class BillingEntity < ApplicationRecord
  has_many :bills
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :patient_entries
end

app/models/duty_entity.rb
class DutyEntity < ApplicationRecord
  has_many :duty_sheets
end

app/models/duty_sheet.rb
class DutySheet < ApplicationRecord
  belongs_to :employee
  belongs_to :ward
  belongs_to :duty_entity
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :employee_type
  has_many :duty_sheets
end

app/models/employee_type.rb
class EmployeeType < ApplicationRecord
  has_many :employees
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :shift
end

app/models/medicine.rb
class Medicine < ApplicationRecord
  belongs_to :patient_entry
end

app/models/patient_entry.rb
class PatientEntry < ApplicationRecord
  has_many :bills
  has_many :medicines
  has_many :test_reports
  belongs_to :department
  belongs_to :patient_registration
  belongs_to :patient_registration_type
  belongs_to :doctor_appointment_sheet
end

app/models/shift.rb
class Shift < ApplicationRecord
  has_many :groups
end

app/models/test_report.rb
class TestReport < ApplicationRecord
  belongs_to :patient_entry
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :ward_type
  has_many :duty_sheets
end

app/models/ward_type.rb
class WardType < ApplicationRecord
  has_many :wards
end

app/controllers/shared_controller.rb
class SharedController < ApplicationController

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/patient_helper.rb
module PatientHelper
  def gender(val)
    gender = {"1" => "Male", "2" => "Female", "3" => "Others"}
    gender[val]
  end
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_feature_navigation.html.erb
<div class="vertical-menu">
  <%= link_to root_path do %>
    <i class="fas fa-tachometer-alt"></i>Dashboard
  <% end %>
  <%= link_to root_path do %>
    <i class="fas fa-ambulance"></i>Entries
  <% end %>
  <%= link_to patient_registrations_path do %>
    <i class="fas fa-bed"></i>Patients
  <% end %>
  <%= link_to employees_path do %>
    <i class="fas fa-user-tie"></i>Employees
  <% end %>
  <%= link_to departments_path do %>
    <i class="fas fa-boxes"></i>Departments
  <% end %>
  <%= link_to duty_sheets_path do %>
    <i class="fas fa-hard-hat"></i>Duties
  <% end %>
  <%= link_to root_path do %>
    <i class="fas fa-user-md"></i>Doctors
  <% end %>
  <%= link_to root_path do %>
    <i class="fas fa-file-invoice-dollar"></i>Bills
  <% end %>
</div>

app/views/shared/_headers.html.erb
<title>HMS - Hospital Management System</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Comfortaa|Montserrat|Open+Sans" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

app/views/shared/_primary_navigation.html.erb
<nav class="navbar navbar-inverse">
   <div class="container-fluid">
   <div class="navbar-header">
     <a class="navbar-brand logo" href="<%= root_path %>">HM System</a>
   </div>
   <ul class="nav navbar-nav">
     <li>
       <%= link_to edit_user_registration_path do %>
         <i class="fas fa-user nav-icon-li"></i>
       <% end %>
     </li>
     <li>
       <%= link_to destroy_user_session_path, :method => :delete do %>
         <i class="fas fa-power-off nav-icon-li"></i>
       <% end %>
     </li>
   </ul>
   </div>
 </nav>